# Generated by Django 4.0.7 on 2023-03-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contry',
            new_name='country',
        ),
    ]
