# Generated by Django 4.0.7 on 2023-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_product',
            name='ammount',
            field=models.IntegerField(default=1),
        ),
    ]
