# Generated by Django 4.0.7 on 2023-03-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='quantity',
        ),
    ]
