# Generated by Django 4.0.7 on 2023-03-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='ammount',
            field=models.IntegerField(default=1),
        ),
    ]
